### ISSUE TITLE
always get this error.

### ISSUE THREAD

**Issue by LiadAvramov** [Kosat/telegram-messages-dump#12] opened 2018-04-24 13:26 UTC
Nobody is using this username, or the username is unacceptable. If the latter,
it must match r"[a-zA-Z][\\w\\d]{3,30}[a-zA-Z\\d]"'). are you familiar with it ?

**Comment by fxcp** [comment] 2018-04-24 14:44
No, we are not. Can you provide example of used username?
Also, try it with issue-6 branch from my fork ([here](https://github.com/fxcp/telegram-messages-dump/tree/issue-6)).

**Comment by LiadAvramov** [comment] 2018-04-24 14:52
offir56 is an example. I chose it according to telegram specification "You can use a-z, 0-9 and underscores. Minimum length is 5 characters."
I tried it with branch 6 in the first place :)

**Comment by fxcp** [comment] 2018-04-24 15:13
It's strange because I'm getting this error instead: `ValueError: Error: failed to resolve chat name into chat_id
` (using code from any branch). However, it looks like PM resolution is broken for ResolveUsernameRequest fallback. e5e7a437087860b88ceff911e87ca5c6b95dcbf4 fixed problem for me.

**Comment by Kosat** [comment] 2018-04-28 14:25
@liad1234 This error means that the tool couldn't resolve the chat name you specified.  You can try to grab the latest sources and try it again. There are significant changes merged in from @fxcp in this area.
Or you can post the exact command line expression that you've used and I'll try to reproduce it on my machine.

**Comment by Kosat** [comment] 2018-05-13 15:51
Closing due to inactivity.
Please, feel free to open a new issue if this or other problem occurs.

**Closed as completed by Kosat** 2018-05-13 15:51 UTC
